int search_yoyaku( int mode, char *tok_buf, int *d_len );
void shift_r_buf( int pos );
void cut_last_space( int mode, char *s );
int get_block( int mode, char *d_buf, char *s_buf, int *tok_len );
int make_map_ctype( char *s_buf );
int chk_hex( char *s_buf );
int chk_asm( void );
int chk_cpluss( void );
int chk_line( char *s_buf );
void store_comment( int mode );
int position_save( int mode, int tag_point );
int store_if( int mode );
int chk_casting( int type, char *s_buf );
void save_out_syori( int mode );
void chk_w_p_m( char *s_buf );
int chk_last_pos( char *s_buf, int pos );
int chk_last_else( char *s_buf );
void chk_for_only( char *s_buf );
int chk_w_kakko( char *s_buf );
int chk_big_kakko( char *s_buf, int *last_pos );
int get_head_tab_pos( char *s_buf );
void tab_to_soh( char *s_buf );
int get_first_pos( char *s_buf );
void big_kakko_syori1( int mode, char *tok_buf );
void big_kakko_syori2( char *tok_buf );
void add_r_kakko_spase( void );
void kyotu_syori( char *tok_buf );
int check_sitei_moji( char *s_buf, char moji );
int chk_comment( char *s_buf );
int search_end_comment( char *s_buf );
void comment_syori1( char *tok_buf, int *tok_len );
void comment_syori2( char *tok_buf, int *tok_len );
void comment_syori4( char *tok_buf, int *tok_len );
void comment_syori5( char *tok_buf, int *tok_len );
void defif_syori( char *tok_buf, int *tok_len );
void endif_syori( char *tok_buf, int *tok_len );
void include_syori( char *tok_buf, int *tok_len );
void define_syori( char *tok_buf, int *tok_len );
void pragma_syori( char *tok_buf, int *tok_len );
void define_another_syori( char *tok_buf, int *tok_len );
int chk_yen( char *s_buf );
void get_next_line( int mode );
int get_line_type( void );
void big_kakko_syori3( int mode, char *tok_buf, int *tok_len );
void if_syori( char *tok_buf, int *tok_len );
void else_syori( char *tok_buf, int *tok_len );
void switch_syori( char *tok_buf, int *tok_len );
void case_syori( char *tok_buf );
void for_syori( char *tok_buf, int *tok_len );
void while_syori( char *tok_buf, int *tok_len );
void do_syori( char *tok_buf, int *tok_len );
void try_syori( char *tok_buf, int *tok_len );
void shl_syori( char *tok_buf, int *tok_len );
void struct_syori( char *tok_buf, int *tok_len );
void union_syori( char *tok_buf, int *tok_len );
int chk_return_kakko( char *s_buf );
void return_syori( char *tok_buf, int *tok_len );
void chk_yoyaku( char *tok_buf );
void refresh( void );
