int get_key( void );
int moji_check( char moji );
int key_sens( void );
int wait_key( char mode );
int _isalpha( int moji );
int _isupper( int moji );
int _islower( int moji );
int _isdigit( int moji );
int _isxdigit( int moji );
int _isspace( int moji );
int _ispunct( int moji );
int _isalnum( int moji );
int _isprint( int moji );
int _isgraph( int moji );
int _iscntrl( int moji );
void obj_bcd2( int obj_data, char *wr_buf );
void get_debug_type_map( char *d_buf, int t_type );
int get_tok1( int mode, char *d_buf, char *s_buf, int *tok_len );
int get_tok2( char *tok_buf, char *s_buf, int *tok_len );
int get_tok3( char *tok_buf, char *s_buf, int *tok_len );
int get_tok4( char *tok_buf, char *s_buf, int *tok_len );
int add_comment( char *s_buf );
int add_b_k_l( char *s_buf );
int kaiseki_typedef( char *s_buf );
int add_bind_macro( char *s_buf );
int chk_type( char *s_buf );
int add_bind_type1( char *s_buf );
int add_bind_type2( int tmp_line, char *s_buf );
int get_define_no2( char *tok_buf, char *s_buf, int *tok_len );
int add_space_one( int end_pos, char *s_buf );
int arrange_tab_soh( int target_pos, int buf_end_pos, char *s_buf );
void open_tab_pos( int mode, int tmp_line );
void open_tab_mes( int tmp_line );
int chk_loop_end( char *s_buf );
int chk_tab_enable( int now_line );
int chk_same_teigi( int base_type, int skip_mes, int *line_no, int end_line );
int get_source_pos( int end_pos, char *t_buf, char *s_buf );
int set_tab( int teigi_no, int line_start, int line_last, int max_pos );
void comment_syori( int base_type, int *line_start, int line_last );
void chk_const_pos( int mode, int line_start, int line_last );
int chk_teigi_tab_max( int mode, int line_start, int line_last );
void pair_kakko_parts( int mode, int line_start, int line_last );
void pair_kakko_arrange( int base_type, int line_start, int line_last );
void teigi_zero_syori( int line_start, int line_last );
void g_asm_syori( int base_type, int line_start, int line_last );
void ajust_tab( int base_type, int line_start, int line_last );
int save_dst_file( void );
std::string UTF8toSjis( std::string srcUTF8 );
std::string SjistoUTF8( std::string srcSjis );
